name: wc_dart_framework
description: Dart framework to provide common code for projects
version: 1.7.0
homepage: https://github.com/aarajput/wc_framework/tree/main/wc_dart_framework
repository: https://github.com/aarajput/wc_framework
issue_tracker: https://github.com/aarajput/wc_framework/issues
documentation: https://github.com/aarajput/wc_framework/blob/main/wc_dart_framework/README.md

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  logging: ^1.2.0
  ansicolor: ^2.0.1

dev_dependencies:
  flutter_lints: 3.0.1

