name: example
description: example of wc_dart_framework

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  wc_dart_framework: 1.0.0

dependency_overrides:
  wc_dart_framework:
    path: ../

dev_dependencies:
  wc_dart_framework_generator:
    path: ../../wc_dart_framework_generator
  build_runner: 2.3.3

flutter:
  assets:
    - assets/
