name: example
description: example of wc_dart_framework

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  wc_dart_framework: 1.8.0
  built_value: 8.9.3
  built_collection: 5.1.1
  hydrated_bloc: 10.0.0
  bloc: 9.0.0
  flutter_bloc: 9.0.0
  meta: 1.15.0
  path_provider: 2.1.5

dependency_overrides:
  flutter_lints: 3.0.1
  wc_dart_framework:
    path: ../

dev_dependencies:
  wc_dart_framework_generator:
    path: ../../wc_dart_framework_generator
  build_runner: 2.4.14
  built_value_generator: 8.9.3

flutter:
  assets:
    - assets/

scripts: derry.yaml