name: example
description: example of wc_dart_framework

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  wc_dart_framework: 1.4.0
  built_value: 8.6.1
  built_collection: 5.1.1
  hydrated_bloc: 9.1.0
  bloc: 8.1.2
  flutter_bloc: 8.1.3
  meta: 1.9.1
  path_provider: 2.0.15

dependency_overrides:
  flutter_lints: 2.0.1
  wc_dart_framework:
    path: ../
  hydrated_bloc:
    git:
      url: https://github.com/aarajput/bloc.git
      path: packages/hydrated_bloc


dev_dependencies:
  wc_dart_framework_generator:
    path: ../../wc_dart_framework_generator
  build_runner: 2.4.6
  built_value_generator: 8.6.1

flutter:
  assets:
    - assets/

scripts: derry.yaml