name: example
description: example of wc_dart_framework

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  wc_dart_framework: 1.0.0
  built_value: 8.4.3
  built_collection: 5.1.1
  hydrated_bloc: 9.1.0
  bloc: 8.1.1
  flutter_bloc: 8.1.2
  meta: 1.8.0

dependency_overrides:
  flutter_lints: 2.0.1
  wc_dart_framework:
    path: ../

dev_dependencies:
  wc_dart_framework_generator:
    path: ../../wc_dart_framework_generator
  build_runner: 2.3.3
  built_value_generator: 8.4.3

flutter:
  assets:
    - assets/

scripts: derry.yaml